[package]
name = "ammonia"
version = "0.1.1"
authors = ["Michael Howell <michael@notriddle.com>"]
description = "HTML Sanitization"
keywords = [ "sanitization", "html" ]
license = "Apache-2.0"
readme = "README.md"
documentation = "https://www.notriddle.com/rustdoc/ammonia/index.html"
repository = "https://github.com/notriddle/rust-ammonia"

[features]
unstable = [ "html5ever/unstable", "tendril/unstable", "string_cache/unstable" ]

[dependencies]
html5ever = "0.2.11"
tendril = "0.1.3"
string_cache = "0.2.0"
grabbag_macros = "0.1.0"
url = "0.2.37"

