[package]
name = "ammonia"
version = "0.1.0"
authors = ["Michael Howell <michael@notriddle.com>"]

[dependencies]
html5ever = "0.2.0"
tendril = "0.1.3"
string_cache = "0.1.8"
grabbag_macros = "0.1.0"
url = "0.2.37"

