[package]
name = "ammonia"
version = "0.1.2"
authors = ["Michael Howell <michael@notriddle.com>"]
description = "HTML Sanitization"
keywords = [ "sanitization", "html" ]
license = "MIT / Apache-2.0"
readme = "README.md"
documentation = "https://www.notriddle.com/rustdoc/ammonia/index.html"
repository = "https://github.com/notriddle/ammonia"

[features]
unstable = [ "html5ever/unstable", "tendril/unstable", "string_cache/unstable" ]

[dependencies]
html5ever = "0.5.4"
maplit = "0.1.3"
tendril = "0.2.2"
string_cache = "0.2.20"
url = "1.1.1"

